# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmodel.proto\x12\x05model\"/\n\x14ModelFeaturesRequest\x12\x17\n\x0fprocessed_image\x18\x01 \x01(\x0c\"8\n\x13ModelOutputResponse\x12\r\n\x05guess\x18\x01 \x01(\x05\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x32V\n\tPredictor\x12I\n\x0cPredictImage\x12\x1b.model.ModelFeaturesRequest\x1a\x1a.model.ModelOutputResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'model_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MODELFEATURESREQUEST._serialized_start=22
  _MODELFEATURESREQUEST._serialized_end=69
  _MODELOUTPUTRESPONSE._serialized_start=71
  _MODELOUTPUTRESPONSE._serialized_end=127
  _PREDICTOR._serialized_start=129
  _PREDICTOR._serialized_end=215
# @@protoc_insertion_point(module_scope)
